### ISSUE TITLE
see if making fixed length wav files and playing back to back improves timing issues. I.e: Mix_PlayChannel( -1, drum1_sound, -1 ); to loop indefinitely

### ISSUE THREAD

**Issue by OllyK** [heffalumpteam/project#6]
Making and wav with a fixed length of 1/4 bar and playing a certain number of times might be one way of solving timing issues

**Comment by heffalumpteam** [comment]
What was the result of this?

**Comment by berkmolla** [comment]
It was successful. Should we maybe phrase the issues differently if closing an issue doesn’t automatically imply that it was successful?
