### ISSUE TITLE
Read in some text from the gtksourceview

### ISSUE THREAD

**Issue by OllyK** [heffalumpteam/project#7]
Starting point to user interaction with our new pseudo-language

**Comment by heffalumpteam** [comment]
This is the lib that GTK uses for text and fonts: https://developer.gnome.org/pango/stable/

found from here: https://developer.gnome.org/references

**Comment by tomrbland** [comment]
How do we link sBuf to the gtksource view? Or is it automatically? Experiments with gtktextview will help this.
